### ISSUE TITLE
"panic: no parser driver " on AL2023 while executing osc

### ISSUE THREAD

**Issue by reillski** [cashapp/spirit#237]
Hey team,
I tried to take spirit for a spin but I'm getting an error on the `main` branch when I try to execute a OSC. Out of curiosity I tried on the `mtocker-add-8.1-8.2` branch, which excludes some changes that were made to the parser location and the OSC started successfully.

Incl. info below.

Thanks!

**Setup steps used on Amazon Linux 2023 on ec2(similar results on ubuntu 22.04):**
```
wget https://go.dev/dl/go1.21.4.linux-amd64.tar.gz
sudo sh -c "rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin" >> .bashrc
source .bashrc
sudo yum install git -y
git clone https://github.com/cashapp/spirit.git
cd spirit/cmd/spirit
go build
```

Output:
```
$ go build
go: downloading github.com/alecthomas/kong v0.7.1
go: downloading github.com/go-mysql-org/go-mysql v1.7.1-0.20231020082131-3a75f6a26d88
go: downloading github.com/siddontang/go-log v0.0.0-20190221022429-1e957dd83bed
go: downloading github.com/siddontang/loggers v1.0.3
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading github.com/pingcap/tidb/pkg/parser v0.0.0-20231031161236-4667ed9e1684
go: downloading github.com/pingcap/tidb v1.1.0-beta.0.20231031161236-4667ed9e1684
go: downloading golang.org/x/sync v0.4.0
go: downloading github.com/go-sql-driver/mysql v1.7.1
go: downloading golang.org/x/exp v0.0.0-20231006140011-7918f672742d
go: downloading github.com/Masterminds/semver v1.5.0
go: downloading github.com/google/uuid v1.4.0
go: downloading github.com/pingcap/errors v0.11.5-0.20221009092201-b66cddb77c32
go: downloading github.com/siddontang/go v0.0.0-20180604090527-bdc77568d726
go: downloading golang.org/x/sys v0.13.0
go: downloading github.com/pingcap/failpoint v0.0.0-20220801062533-2eaa32854a6c
go: downloading github.com/BurntSushi/toml v1.3.2
go: downloading github.com/pingcap/tidb/parser v0.0.0-20221126021158-6b02a5d8ba7d
go: downloading github.com/shopspring/decimal v1.3.1
go: downloading github.com/klauspost/compress v1.17.1
go: downloading go.uber.org/atomic v1.11.0
go: downloading github.com/pingcap/log v1.1.1-0.20230317032135-a0d097d16e22
go: downloading go.uber.org/zap v1.26.0
go: downloading golang.org/x/text v0.13.0
go: downloading github.com/cznic/mathutil v0.0.0-20181122101859-297441e03548
go: downloading gopkg.in/natefinch/lumberjack.v2 v2.2.1
go: downloading go.uber.org/multierr v1.11.0
go: downloading github.com/remyoudompheng/bigfft v0.0.0-20230129092748-24d4a6f8daec
```

**Error on `main`:**
```
[ec2-user@ip-10-0-8-113 spirit]$ ./spirit \
--host="10.0.8.196:3306" \
--username="user" \
--password="password" \
--database="tpcc_30000wh" \
--table="stock" \
--alter="add index idx2(s_dist_01)" \
--threads=20 \
--target-chunk-time=500ms \
--checksum \
--lock-wait-timeout=30s \
--skip-drop-after-cutover
INFO[0000] Starting spirit migration: concurrency=20 target-chunk-size=500ms table=tpcc_30000wh.stock alter="add index idx2(s_dist_01)"
panic: no parser driver (forgotten import?) https://github.com/pingcap/parser/issues/43

goroutine 1 [running]:
github.com/pingcap/tidb/pkg/parser.New()
	/home/ec2-user/go/pkg/mod/github.com/pingcap/tidb/pkg/parser@v0.0.0-20231031161236-4667ed9e1684/yy_parser.go:121 +0x105
github.com/cashapp/spirit/pkg/check.dropAddCheck({0x1d99870?, 0x0?}, {0xc000306340, 0x0, 0xc0002966c0, {0xc000121240, 0x19}, 0x1dcd6500, 0x14, 0x1bf08eb000, ...}, ...)
	/home/ec2-user/spirit/pkg/check/dropadd.go:24 +0xb8
github.com/cashapp/spirit/pkg/check.RunChecks({0xd6fab8, 0xc00030a050}, {0xc000306340, 0x0, 0xc0002966c0, {0xc000121240, 0x19}, 0x1dcd6500, 0x14, 0x1bf08eb000, ...}, ...)
	/home/ec2-user/spirit/pkg/check/check.go:69 +0x116
github.com/cashapp/spirit/pkg/migration.(*Runner).runChecks(0xc0000da630?, {0xd6fab8, 0xc00030a050}, 0x2?)
	/home/ec2-user/spirit/pkg/migration/runner.go:341 +0x17e
github.com/cashapp/spirit/pkg/migration.(*Runner).Run(0xc0000da630, {0xd6f9d8?, 0x1e417e0?})
	/home/ec2-user/spirit/pkg/migration/runner.go:195 +0x676
github.com/cashapp/spirit/pkg/migration.(*Migration).Run(0x1e103e0)
	/home/ec2-user/spirit/pkg/migration/migration.go:44 +0xa5
reflect.Value.call({0xb53580?, 0x1e103e0?, 0x0?}, {0xc1ad27, 0x4}, {0xc00008bae0, 0x0, 0xade118?})
	/usr/local/go/src/reflect/value.go:596 +0xce7
reflect.Value.Call({0xb53580?, 0x1e103e0?, 0xb61340?}, {0xc00008bae0?, 0xc00009a1c8?, 0xc00008bb20?})
	/usr/local/go/src/reflect/value.go:380 +0xb9
github.com/alecthomas/kong.callMethod({0xc1a943, 0x3}, {0xb697c0?, 0x1e103e0?, 0xb96640?}, {0xb53580?, 0x1e103e0?, 0x48e112?}, 0xadd29d?)
	/home/ec2-user/go/pkg/mod/github.com/alecthomas/kong@v0.7.1/callbacks.go:95 +0x4db
github.com/alecthomas/kong.(*Context).RunNode(0xc0001ed780, 0xc00026c000, {0x0, 0x0, 0x3?})
	/home/ec2-user/go/pkg/mod/github.com/alecthomas/kong@v0.7.1/context.go:755 +0x845
github.com/alecthomas/kong.(*Context).Run(0xc0001ed780, {0x0, 0x0, 0x0})
	/home/ec2-user/go/pkg/mod/github.com/alecthomas/kong@v0.7.1/context.go:774 +0xfd
main.main()
	/home/ec2-user/spirit/cmd/spirit/main.go:14 +0x39
[ec2-user@ip-10-0-8-113 spirit]$
```

On `mtocker-add-8.1-8.2` branch:
```
[ec2-user@ip-10-0-8-43 spirit]$ ./spirit --host="10.0.8.196:3306" --username="user" --password="password" --database="tpcc_30000wh" --table="stock" --alter="add index idx2(s_dist_01)" --threads=10 --target-chun
k-time=500ms --checksum --lock-wait-timeout=30s --skip-drop-after-cutover
INFO[0000] Starting spirit migration: concurrency=10 target-chunk-size=500ms table=tpcc_30000wh.stock alter="add index idx2(s_dist_01)"
INFO[0000] could not resume from checkpoint: reason=could not read from table '_stock_new'
INFO[0000] create BinlogSyncer with config {1430 mysql 10.0.8.196 3306 user   utf8 false false <nil> false UTC false 0 0s 0s 0 false false 0 <nil> 0xc00029a700 0x7059e0 <nil> false}
INFO[0000] skip dump, use last binlog replication pos (mysql-bin-changelog.001981, 120080406) or GTID set <nil>
INFO[0000] begin to sync binlog from position (mysql-bin-changelog.001981, 120080406)
INFO[0000] start sync binlog at binlog file (mysql-bin-changelog.001981, 120080406)
INFO[0030] migration status: state=copyRows copy-progress=4551066/2962232747 0.15% binlog-deltas=20210 total-time=30s copier-time=30s copier-remaining-time=TBD copier-is-throttled=false conns-in-use=10
INFO[0050] checkpoint: low-watermark={"Key":["s_w_id","s_i_id"],"ChunkSize":5762,"LowerBound":{"Value": ["52","32014"],"Inclusive":true},"UpperBound":{"Value": ["52","37777"],"Inclusive":false}} log-file=mysql-bin-
changelog.001981 log-pos=120080406 rows-copied=5150100 rows-copied-logical=5149319
INFO[0060] migration status: state=copyRows copy-progress=5387777/2962232747 0.18% binlog-deltas=26180 total-time=1m0s copier-time=1m0s copier-remaining-time=32h51m13s copier-is-throttled=false conns-in-use=11
INFO[0090] migration status: state=copyRows copy-progress=6130974/2962232747 0.21% binlog-deltas=45915 total-time=1m30s copier-time=1m30s copier-remaining-time=33h2m9s copier-is-throttled=false conns-in-use=11
INFO[0100] checkpoint: low-watermark={"Key":["s_w_id","s_i_id"],"ChunkSize":6401,"LowerBound":{"Value": ["64","70673"],"Inclusive":true},"UpperBound":{"Value": ["64","77075"],"Inclusive":false}} log-file=mysql-bin-changelog.001981 log-pos=120080406 rows-copied=6389878 rows-copied-logical=6388895
.
.
.
```

**Comment by reillski** [comment]
That done the trick, thanks!
