### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by jayjanssen** [cashapp/spirit#335]
```
panic: runtime error: integer divide by zero

goroutine 55 [running]:
github.com/cashapp/spirit/pkg/repl.(*Client).flushMap(0xc0002a2240, {0xcef038, 0xc0003da460}, 0x0, 0x0)
	/spirit/src/pkg/repl/client.go:517 +0xb4e
github.com/cashapp/spirit/pkg/repl.(*Client).flush(0xc0004e5f68?, {0xcef038?, 0xc0003da460?}, 0x0?, 0xc000324e40?)
	/spirit/src/pkg/repl/client.go:418 +0x32
github.com/cashapp/spirit/pkg/repl.(*Client).StartPeriodicFlush(0xc0002a2240, {0xcef038, 0xc0003da460}, 0x6fc23ac00)
	/spirit/src/pkg/repl/client.go:690 +0x294
created by github.com/cashapp/spirit/pkg/migration.(*Runner).setup in goroutine 1
	/spirit/src/pkg/migration/runner.go:541 +0x96c
```

Full log:
```
Starting prechecks for migration 3281
Starting migration 3281
time="2024-08-06T16:28:29Z" level=info msg="Starting spirit migration: concurrency=1 target-chunk-size=100ms table=ods-aurora-test_development.sbtest1 alter=\"ENGINE=INNODB\""
time="2024-08-06T16:28:30Z" level=info msg="attempting to acquire metadata lock: spirit_ods-aurora-test_development_sbtest1"
time="2024-08-06T16:28:30Z" level=info msg="acquired metadata lock: spirit_ods-aurora-test_development_sbtest1"
time="2024-08-06T16:28:31Z" level=info msg="unable to use INPLACE: ALTER either does not support INPLACE or when performed as INPLACE could take considerable time. Use --force-inplace to override this safety check"
time="2024-08-06T16:28:32Z" level=info msg="could not resume from checkpoint: reason=could not read from table '_sbtest1_new'"
time="2024-08-06T16:28:34Z" level=info msg="create BinlogSyncer with config {ServerID:1131 Flavor:mysql Host:ods-aurora-test-development-aurora-use1-002.cluster-ctbvkxlssqcn.us-east-1.rds.amazonaws.com Port:3306 User:spirit Password: Localhost: Charset:utf8 SemiSyncEnabled:false RawModeEnabled:false TLSConfig:0xc00009c000 ParseTime:false TimestampStringLocation:UTC UseDecimal:false RecvBufferSize:0 HeartbeatPeriod:0s ReadTimeout:0s MaxReconnectAttempts:0 DisableRetrySync:false VerifyChecksum:false DumpCommandFlag:0 Option:<nil> Logger:0xc00040d680 Dialer:0x787100 RowsEventDecodeFunc:0xa5b960 TableMapOptionalMetaDecodeFunc:<nil> DiscardGTIDSet:false EventCacheCount:10240}"
time="2024-08-06T16:28:34Z" level=info msg="skip dump, use last binlog replication pos (mysql-bin-changelog.007667, 39548000) or GTID set <nil>"
time="2024-08-06T16:28:34Z" level=info msg="begin to sync binlog from position (mysql-bin-changelog.007667, 39548000)"
time="2024-08-06T16:28:35Z" level=info msg="start sync binlog at binlog file (mysql-bin-changelog.007667, 39548000)"
time="2024-08-06T16:29:04Z" level=info msg="migration status: state=copyRows copy-progress=17105/115000000 0.01% binlog-deltas=94 total-time=35s copier-time=30s copier-remaining-time=TBD copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:29:05Z" level=info msg="finished periodic flush of binary log: total-duration=858.441912ms batch-size=1000"
time="2024-08-06T16:29:24Z" level=info msg="checkpoint: low-watermark={\"Key\":[\"id\"],\"ChunkSize\":10,\"LowerBound\":{\"Value\": [\"16836\"],\"Inclusive\":true},\"UpperBound\":{\"Value\": [\"16846\"],\"Inclusive\":false}} log-file=mysql-bin-changelog.007667 log-pos=70798511 rows-copied=16845 rows-copied-logical=17845"
time="2024-08-06T16:29:34Z" level=info msg="migration status: state=copyRows copy-progress=18225/115000000 0.02% binlog-deltas=119 total-time=1m5s copier-time=1m0s copier-remaining-time=840h30m36s copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:29:35Z" level=info msg="finished periodic flush of binary log: total-duration=395.555754ms batch-size=1000"
time="2024-08-06T16:30:04Z" level=info msg="migration status: state=copyRows copy-progress=19345/115000000 0.02% binlog-deltas=127 total-time=1m35s copier-time=1m30s copier-remaining-time=840h30m6s (±0m from 1m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:30:05Z" level=info msg="finished periodic flush of binary log: total-duration=397.599518ms batch-size=1000"
time="2024-08-06T16:30:14Z" level=info msg="checkpoint: low-watermark={\"Key\":[\"id\"],\"ChunkSize\":10,\"LowerBound\":{\"Value\": [\"18706\"],\"Inclusive\":true},\"UpperBound\":{\"Value\": [\"18716\"],\"Inclusive\":false}} log-file=mysql-bin-changelog.007667 log-pos=128424248 rows-copied=18715 rows-copied-logical=19715"
time="2024-08-06T16:30:34Z" level=info msg="migration status: state=copyRows copy-progress=20455/115000000 0.02% binlog-deltas=122 total-time=2m5s copier-time=2m0s copier-remaining-time=863h12m35s (-22h43m from 1m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:30:35Z" level=info msg="finished periodic flush of binary log: total-duration=399.05747ms batch-size=1000"
time="2024-08-06T16:31:04Z" level=info msg="migration status: state=copyRows copy-progress=21575/115000000 0.02% binlog-deltas=176 total-time=2m35s copier-time=2m30s copier-remaining-time=863h12m5s (-22h43m from 2m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:31:04Z" level=info msg="checkpoint: low-watermark={\"Key\":[\"id\"],\"ChunkSize\":10,\"LowerBound\":{\"Value\": [\"20566\"],\"Inclusive\":true},\"UpperBound\":{\"Value\": [\"20576\"],\"Inclusive\":false}} log-file=mysql-bin-changelog.007668 log-pos=22677675 rows-copied=20575 rows-copied-logical=21575"
time="2024-08-06T16:31:05Z" level=info msg="finished periodic flush of binary log: total-duration=404.534276ms batch-size=1000"
time="2024-08-06T16:31:34Z" level=info msg="migration status: state=copyRows copy-progress=22715/115000000 0.02% binlog-deltas=156 total-time=3m5s copier-time=3m0s copier-remaining-time=840h28m38s (±0m from 2m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:31:35Z" level=info msg="finished periodic flush of binary log: total-duration=883.62343ms batch-size=1000"
time="2024-08-06T16:31:54Z" level=info msg="checkpoint: low-watermark={\"Key\":[\"id\"],\"ChunkSize\":10,\"LowerBound\":{\"Value\": [\"22466\"],\"Inclusive\":true},\"UpperBound\":{\"Value\": [\"22476\"],\"Inclusive\":false}} log-file=mysql-bin-changelog.007668 log-pos=80012213 rows-copied=22475 rows-copied-logical=23475"
time="2024-08-06T16:32:04Z" level=info msg="migration status: state=copyRows copy-progress=23855/115000000 0.02% binlog-deltas=162 total-time=3m35s copier-time=3m30s copier-remaining-time=840h28m8s (±0m from 3m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:32:05Z" level=info msg="finished periodic flush of binary log: total-duration=409.497362ms batch-size=1000"
time="2024-08-06T16:32:34Z" level=info msg="migration status: state=copyRows copy-progress=24955/115000000 0.02% binlog-deltas=184 total-time=4m5s copier-time=4m0s copier-remaining-time=887h9m11s (-46h42m from 3m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:32:35Z" level=info msg="finished periodic flush of binary log: total-duration=892.031939ms batch-size=1000"
time="2024-08-06T16:32:44Z" level=info msg="checkpoint: low-watermark={\"Key\":[\"id\"],\"ChunkSize\":10,\"LowerBound\":{\"Value\": [\"24316\"],\"Inclusive\":true},\"UpperBound\":{\"Value\": [\"24326\"],\"Inclusive\":false}} log-file=mysql-bin-changelog.007669 log-pos=4451898 rows-copied=24325 rows-copied-logical=25325"
time="2024-08-06T16:33:04Z" level=info msg="migration status: state=copyRows copy-progress=26065/115000000 0.02% binlog-deltas=181 total-time=4m35s copier-time=4m30s copier-remaining-time=863h10m3s (-22h43m from 4m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:33:05Z" level=info msg="finished periodic flush of binary log: total-duration=415.219265ms batch-size=1000"
time="2024-08-06T16:33:34Z" level=info msg="checkpoint: low-watermark={\"Key\":[\"id\"],\"ChunkSize\":10,\"LowerBound\":{\"Value\": [\"26166\"],\"Inclusive\":true},\"UpperBound\":{\"Value\": [\"26176\"],\"Inclusive\":false}} log-file=mysql-bin-changelog.007669 log-pos=33965183 rows-copied=26175 rows-copied-logical=27175"
time="2024-08-06T16:33:35Z" level=info msg="finished periodic flush of binary log: total-duration=587.579663ms batch-size=44"
time="2024-08-06T16:33:35Z" level=info msg="table statistics updated: estimated-rows=114049167 pk[0].max-value=115000000"
time="2024-08-06T16:33:35Z" level=info msg="migration status: state=copyRows copy-progress=27175/115000000 0.02% binlog-deltas=8 total-time=5m6s copier-time=5m1s copier-remaining-time=863h9m33s (-22h43m from 4m ago) copier-is-throttled=false conns-in-use=0"
time="2024-08-06T16:34:04Z" level=info msg="migration status: state=copyRows copy-progress=28275/115000000 0.02% binlog-deltas=2 total-time=5m35s copier-time=5m30s copier-remaining-time=863h9m3s (-22h43m from 4m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:34:07Z" level=info msg="finished periodic flush of binary log: total-duration=2.442522416s batch-size=44"
time="2024-08-06T16:34:24Z" level=info msg="checkpoint: low-watermark={\"Key\":[\"id\"],\"ChunkSize\":10,\"LowerBound\":{\"Value\": [\"27996\"],\"Inclusive\":true},\"UpperBound\":{\"Value\": [\"28006\"],\"Inclusive\":false}} log-file=mysql-bin-changelog.007669 log-pos=93038505 rows-copied=28005 rows-copied-logical=29005"
time="2024-08-06T16:34:34Z" level=info msg="migration status: state=copyRows copy-progress=29375/115000000 0.03% binlog-deltas=2 total-time=6m5s copier-time=6m0s copier-remaining-time=863h8m34s (-22h43m from 5m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:34:36Z" level=info msg="high chunk processing time. time: 733.524534ms threshold: 500ms target-rows: 10 target-ms: 100ms new-target-rows: 1"
time="2024-08-06T16:34:37Z" level=info msg="finished periodic flush of binary log: total-duration=2.453651936s batch-size=15"
time="2024-08-06T16:35:04Z" level=info msg="migration status: state=copyRows copy-progress=30495/115000000 0.03% binlog-deltas=12 total-time=6m35s copier-time=6m30s copier-remaining-time=840h25m13s (±0m from 6m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:35:10Z" level=info msg="finished periodic flush of binary log: total-duration=6.131930069s batch-size=5"
time="2024-08-06T16:35:14Z" level=info msg="checkpoint: low-watermark={\"Key\":[\"id\"],\"ChunkSize\":10,\"LowerBound\":{\"Value\": [\"29866\"],\"Inclusive\":true},\"UpperBound\":{\"Value\": [\"29876\"],\"Inclusive\":false}} log-file=mysql-bin-changelog.007670 log-pos=17762836 rows-copied=29875 rows-copied-logical=30875"
time="2024-08-06T16:35:34Z" level=info msg="migration status: state=copyRows copy-progress=31625/115000000 0.03% binlog-deltas=0 total-time=7m5s copier-time=7m0s copier-remaining-time=863h7m33s (-22h43m from 6m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:35:53Z" level=info msg="finished periodic flush of binary log: total-duration=18.429074645s batch-size=1"
time="2024-08-06T16:36:04Z" level=info msg="migration status: state=copyRows copy-progress=32765/115000000 0.03% binlog-deltas=0 total-time=7m35s copier-time=7m30s copier-remaining-time=840h24m13s (±0m from 7m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:36:04Z" level=info msg="checkpoint: low-watermark={\"Key\":[\"id\"],\"ChunkSize\":10,\"LowerBound\":{\"Value\": [\"31756\"],\"Inclusive\":true},\"UpperBound\":{\"Value\": [\"31766\"],\"Inclusive\":false}} log-file=mysql-bin-changelog.007670 log-pos=47146960 rows-copied=31765 rows-copied-logical=32765"
time="2024-08-06T16:36:34Z" level=info msg="migration status: state=copyRows copy-progress=33855/115000000 0.03% binlog-deltas=246 total-time=8m5s copier-time=8m0s copier-remaining-time=863h6m33s (-22h43m from 7m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:36:54Z" level=info msg="checkpoint: low-watermark={\"Key\":[\"id\"],\"ChunkSize\":10,\"LowerBound\":{\"Value\": [\"33566\"],\"Inclusive\":true},\"UpperBound\":{\"Value\": [\"33576\"],\"Inclusive\":false}} log-file=mysql-bin-changelog.007670 log-pos=47146960 rows-copied=33575 rows-copied-logical=34575"
time="2024-08-06T16:37:04Z" level=info msg="migration status: state=copyRows copy-progress=34955/115000000 0.03% binlog-deltas=487 total-time=8m35s copier-time=8m30s copier-remaining-time=840h23m15s (±0m from 8m ago) copier-is-throttled=false conns-in-use=2"
time="2024-08-06T16:37:33Z" level=info msg="finished periodic flush of binary log: total-duration=1m28.525786877s batch-size=0"
panic: runtime error: integer divide by zero

goroutine 55 [running]:
github.com/cashapp/spirit/pkg/repl.(*Client).flushMap(0xc0002a2240, {0xcef038, 0xc0003da460}, 0x0, 0x0)
	/spirit/src/pkg/repl/client.go:517 +0xb4e
github.com/cashapp/spirit/pkg/repl.(*Client).flush(0xc0004e5f68?, {0xcef038?, 0xc0003da460?}, 0x0?, 0xc000324e40?)
	/spirit/src/pkg/repl/client.go:418 +0x32
github.com/cashapp/spirit/pkg/repl.(*Client).StartPeriodicFlush(0xc0002a2240, {0xcef038, 0xc0003da460}, 0x6fc23ac00)
	/spirit/src/pkg/repl/client.go:690 +0x294
created by github.com/cashapp/spirit/pkg/migration.(*Runner).setup in goroutine 1
	/spirit/src/pkg/migration/runner.go:541 +0x96c
```

**Comment by jayjanssen** [comment]
got the same panic with higher load settings too:

```
time="2024-08-06T17:07:14Z" level=info msg="Starting spirit migration: concurrency=16 target-chunk-size=5s table=ods-aurora-test_development.sbtest1 alter=\"ENGINE=INNODB\""
...does a decent amount of copying...

panic: runtime error: integer divide by zero

goroutine 49 [running]:
github.com/cashapp/spirit/pkg/repl.(*Client).flushMap(0xc0002b2480, {0xcef038, 0xc0003ea460}, 0x0, 0x0)
	/spirit/src/pkg/repl/client.go:517 +0xb4e
github.com/cashapp/spirit/pkg/repl.(*Client).flush(0xc00050ff68?, {0xcef038?, 0xc0003ea460?}, 0x0?, 0x0?)
	/spirit/src/pkg/repl/client.go:418 +0x32
github.com/cashapp/spirit/pkg/repl.(*Client).StartPeriodicFlush(0xc0002b2480, {0xcef038, 0xc0003ea460}, 0x6fc23ac00)
	/spirit/src/pkg/repl/client.go:690 +0x294
created by github.com/cashapp/spirit/pkg/migration.(*Runner).setup in goroutine 1
	/spirit/src/pkg/migration/runner.go:541 +0x96c
```

**Comment by morgo** [comment]
It's caused by this:
```
		if (i % target) == 0 {
```

Basically the target batch size is reduced to zero under load. It needs some code to ensure the minimum is 1. I will handle this.
